name:                hannibal
# The package version.  See the Haskell package versioning policy (PVP)
# for standards guiding when and how versions should be incremented.
# https://wiki.haskell.org/Package_versioning_policy
# PVP summary:       +-+------- breaking API changes
#                    | | +----- non-breaking API additions
#                    | | | +--- code changes with no API change
version:             0.1.0.0
github:              "RaphaelJ/hannibal"
license:             GPL3
author:              "Raphael Javaux"
maintainer:          "raphaeljavaux@gmail.com"
copyright:           "2022 Raphael javaux"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Hannibal is a P2P client to share files on a local network
category:            Network

description:         Please see the README on GitHub at <https://github.com/RaphaelJ/hannibal>

dependencies:
- base                  >= 4.7 && < 5
- binary                >= 0.8.8.0 && < 0.9
- bson                  >= 0.4.0.1 && < 0.5
- bytestring            >= 0.10.12.0 && < 0.11
- classy-prelude        >= 1.5.0.2 && < 1.6
- conduit               >= 1.3.4.2 && < 1.5
- conduit-extra         >= 1.3.5 && < 1.4
- binary-conduit        >= 1.3.1 && < 1.4
- containers            >= 0.6.4.1 && < 0.7
- directory-tree        >= 0.12.1 && < 0.13
- filepath              >= 1.4.2.1 && < 1.5
- lz4                   >= 0.2.3.1 && < 0.3
- monad-logger          >= 0.3.36 && < 0.4
- mtl                   >= 2.2.2 && < 2.3
- network               >= 3.1.1.1 && < 3.2
- random                >= 1.2.0 && < 1.3
#- safe-exceptions       >= 0.1.7.3 && < 0.2
- SHA                   >= 1.6.4.4 && < 1.7
- streaming-commons     >= 0.2.2.4 && < 0.3
- text                  >= 1.2.4.1 && < 1.3
- uuid                  >= 1.3.15 && < 1.4
- vector                >= 0.12.3.1 && < 0.13

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  default-extensions:
  - BangPatterns
  - NoImplicitPrelude
  - FlexibleInstances
  - OverloadedStrings
  - RecordWildCards
  - UndecidableInstances
  - TemplateHaskell

executables:
  hannibal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hannibal

tests:
  hannibal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hannibal
